[package]
name = "expack"
version = "0.0.1"
authors = ["landcat222 <67131672+landcat222@users.noreply.github.com>"]
edition = "2018"
description = "Expack is wrapper for any packaging wrappers"

[dependencies]
dirs = "3.0.1"
once_cell = "1.7.2"
